# Generated by Django 2.0.5 on 2018-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20180912_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='img',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
