# Generated by Django 2.0.5 on 2018-10-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_auto_20180919_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='tag',
        ),
        migrations.AddField(
            model_name='programa',
            name='coaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='desarrollo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='salud',
            field=models.BooleanField(default=False),
        ),
    ]
