# Generated by Django 2.0.5 on 2018-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0005_auto_20181009_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
